### ISSUE TITLE
Mark Harman

### ISSUE THREAD

**Issue by zaklinica** [kiwitcms/history-of-testing#80] opened 2022-01-30 15:55 UTC
### What's wrong?

https://en.wikipedia.org/wiki/Mark_Harman_(computer_scientist)

https://scholar.google.com/citations?hl=en&user=IwSN8IgAAAAJ

http://www0.cs.ucl.ac.uk/staff/mharman/

https://www.computer.org/profiles/mark-harman

**missing birth date**

**Comment by atodorov** [comment] 2022-01-30 19:07
Duplicate of #44

**Closed by atodorov** 2022-01-30 19:07 UTC
